name: emoji_picker_flutter_custom
description: Custom wrapper for emoji_picker_flutter with JVM 1.8 compatibility fixes
version: 1.6.4
homepage: https://github.com/RemiBp/flutter_app_badger_fork

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  test: ^1.21.4

flutter:
  plugin:
    platforms:
      android:
        package: com.fintasys.emoji_picker_flutter
        pluginClass: EmojiPickerFlutterPlugin
      ios:
        pluginClass: EmojiPickerFlutterPlugin
      macos:
        pluginClass: EmojiPickerFlutterPlugin
      windows:
        pluginClass: EmojiPickerFlutterPluginCApi
      linux:
        pluginClass: EmojiPickerFlutterPlugin
      web:
        pluginClass: EmojiPickerFlutterPluginWeb
        fileName: emoji_picker_flutter_web.dart
