name: flutter_app_badger 
description: Un plugin Flutter pour ajouter des badges d'application sur les icones d'application. 
version: 1.5.0+1  
homepage: https://github.com/RemiBp/flutter_app_badger_fork  
  
environment: 
