name: firebase_messaging
description: A custom implementation of Firebase Messaging to avoid Android Gradle issues
version: 14.7.10
homepage: https://github.com/RemiBp/flutter_app_badger_fork

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.messaging
        pluginClass: FirebaseMessagingPlugin
      ios:
        pluginClass: FLTFirebaseMessagingPlugin 