name: flutter_local_notifications
description: Une version personnalisée de flutter_local_notifications avec corrections pour les ambiguités Java
version: 14.1.4+2
homepage: https://github.com/RemiBp/Choice/tree/main/plugin/flutter_local_notifications

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications_platform_interface: ^7.0.0
  flutter_local_notifications_linux: ^4.0.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.dexterous.flutterlocalnotifications
        pluginClass: FlutterLocalNotificationsPlugin
      ios:
        pluginClass: FlutterLocalNotificationsPlugin
      macos:
        pluginClass: FlutterLocalNotificationsPlugin
      linux:
        pluginClass: LinuxFlutterLocalNotificationsPlugin
        default_package: flutter_local_notifications_linux 