name: firebase_core
description: A custom implementation of Firebase Core to avoid Android Gradle issues
version: 2.13.0
homepage: https://github.com/YourUsername/firebase_core_custom

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.core
        pluginClass: FirebaseCorePlugin
      ios:
        pluginClass: FirebaseCorePlugin 